# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.7.4
    hooks:
    # https://docs.astral.sh/ruff/settings/
      - id: ruff
        types_or:
          - python
          - pyi
          - jupyter
        args:
          - '--fix'
      - id: ruff-format
        types_or:
          - python
          - pyi
          - jupyter
  - repo: 'https://github.com/python-poetry/poetry'
    rev: 1.8.4
    hooks:
    # https://python-poetry.org/docs/pre-commit-hooks/
      - id: poetry-check
      - id: poetry-export
      - id: poetry-lock
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.13.0
    hooks:
    # https://github.com/pre-commit/mirrors-mypy?tab=readme-ov-file#using-mypy-with-pre-commit
      - id: mypy
  - repo: 'https://github.com/pre-commit/pre-commit'
    rev: v4.0.1
    hooks:
    # https://github.com/pre-commit/pre-commit/blob/main/.pre-commit-hooks.yaml
      - id: validate_manifest
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
    # https://pre-commit.com/hooks.html
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - '--allow-missing-credentials'
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: pretty-format-json
        args:
          - '--autofix'
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/atloo1/check-pyproject-incremented/
    rev: 2f57272e4b099d287fca54ec5542580664fb4c4c
    hooks:
      - id: check-pyproject-incremented
