# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.4.4
    hooks:
    # https://docs.astral.sh/ruff/settings/
      - id: ruff
        types_or:
          - python
          - pyi
          - jupyter
        args:
          - '--fix'
      - id: ruff-format
        types_or:
          - python
          - pyi
          - jupyter
  - repo: 'https://github.com/python-poetry/poetry'
    rev: bea241ffd01855a7013bbc0b4a4825e65429f82d
    hooks:
    # https://python-poetry.org/docs/pre-commit-hooks/
      - id: poetry-check
      - id: poetry-export
      - id: poetry-lock
  - repo: 'https://github.com/pre-commit/pre-commit'
    rev: v3.6.2
    hooks:
      - id: validate_manifest
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
    # https://pre-commit.com/hooks.html
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
         - '--allow-missing-credentials'
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: name-tests-test
      - id: pretty-format-json
        args:
          - '--autofix'
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
