[tool.poetry]
name = "cache-youtube"
version = "1.0.0"
description = "build yt-dlp script for videos in a Watch Later playlist"
authors = ["atloo1"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
